import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'

//components
import Navbar from './components/Navbar'


const inter = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LeaveManagement',
  description: 'Generated by create Heng Somnang',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Navbar />
        </nav>
        {children}</body>
    </html>
  )
}
